---
title: 'GitHub and the Open Science Framework'
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, cache=FALSE, include=FALSE}
library(knitr)
opts_chunk$set(comment='', eval=FALSE)
```

_GitHub_

There are several advantages to using GitHub (or another Git service or versioning system) as well as the Open Science Framework. GitHub first functions as a backup of all your code: you can go back in time to any point you "saved". It also allows easier sharing of code with others, as they can simply check out your GitHub repository. You can create branches to work on improving separate parts of your code, and you can receive pull requests from external people who've tried to make their own improvements. But even when you're just working on code on your own, using GitHub is beneficial.

_The Open Science Framework_

The Open Science Framework (osf.io) started mainly as a repository for data, but can do much more now. It can be integrated with GitHub, it has pre-print servers, and OSF repositories can be registered to get their own DOI, and become cite-able units.

_Working with GitHub and the Open Science Framework_

In this notebook, I'll describe the basics of how to use GitHub from within R Studio, and how to integrate this with an OSF repository. The main idea is to use GitHub for code and development, and OSF as a data repository as well as the main public access point for your science project.

# GitHub

Start by making a GitHub repository, then an R Studio project with version control.

Making a GitHub project requires a GitHub account and from there you can create a new repository. The name of your repository should be memorable (descriptive) but still fairly short, as this will show up in lists of repositories / projects. I'd avoid spaces in repo names, as the GitHub repo name will also become a folder on your computer, and spaces in folder names are still not great. I keep all my GitHub repositories publis, but especially for a scientific project that will become a (published) paper, I would make it public and give it a GPL 3 license to keep it Open Access in all future forms.

At some point before making an R Studio project that is connected to the GitHub repository, you need to install `git` on your computer. When installing `git` it will want to be associated with a text editor. You should pick one you like, or at least know how to use, because sooner or later you will probably need to use for something that R Studio doesn't (yet) do with some fancy buttons. I like Atom, which was made by the people from GitHub, but you should pick whatever you like (as long as it isn't vim).

# Version controlled R Studio project

This part assumes you're already familiar with R Studio Projects. By themselves, R Studio Projects already save you a lot of trouble, and this is compounded by basing your R Studio Project on a GitHub repo. This is why you first make a GitHub repo, and then a project.



# Contributing to another Git repo

In order to directly contribute to someone else's GitHub project, you need to first fork their project. This creates a full copy of the project on your GitHub account. Any project should have a fork button on it, but you can only see/use this when you're logged into your account. Then also declare the "upstream" repo somewhere, in your local git version of the project.

When you type:

```{bash}
git remote -v
```

Into the R Studio Terminal tab, you should get a list of the branches of your git project. There are usually at least two sources, each on their own line. If you didn't link your repo to an upstream git repo yet, those lines start with 'origin'.

You can then add the upstream repository with this command:

```{bash}
git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git
```

Replace the URL with the actual URL for the upstream repository.

If this command completes successfully, the earlier command `git remote -v` should now also have some lines that start with 'upstream'.

Now git is ready to pull in changes from the upstream repository. First, we get a fresh copy of the upstream repository:

```{bash}
git fetch upstream
```

And switch to the local branch (in this case 'master') that we want the upstream changes to be reflected in:

```{bash}
git checkout master
```

And then we can merge the upstream master with the local master:

```{bash}
git merge upstream/master
```

If some changes need to be committed first and you run this from command line, git will drop you into it's standard text editor to write the commit message.

By default this is `vim` which works very differently from what you may be used to. In particular, everything works with keyboard shortcuts. In this case, you can simply edit the one line for the commit message, and then press `Esc` and then `:wq` to save the file and exit `vim`.



How to push merge requests to someone else's GitHub project.



source:
https://help.github.com/articles/syncing-a-fork/


# Open Science Framework

The Open Science Framework (OSF) plays a role that GitHub can not.

You can register projects. Registered projects can't be altered anymore. This guarantees to your readers that you didn't tamper with data files or code after publication.

You can also get a DOI for your data and code so that you can always show that you did something first.

Pick the Canadian file server.